data_dir: /home/nadav2/dev/data/CLIP2Shape/outs/images_to_shape/NeuralBody_DATA/new/data
predictions_dir: /home/nadav2/dev/data/CLIP2Shape/outs/images_to_shape/NeuralBody_DATA/new/predictions
output_dir: /home/nadav2/dev/data/CLIP2Shape/outs/images_to_shape/NeuralBody_DATA/new/smpl_comparison_consensus
gt_dir: /home/nadav2/dev/data/CLIP2Shape/outs/images_to_shape/NeuralBody_DATA/new/data

comparison_kwargs:
  
  raw_imgs_dir: ${data_dir}
  gt_dir: ${gt_dir}
  output_path: ${output_dir}
  
  comparison_dirs:
    # shapy: ${predictions_dir}/shapy_predictions
    spin: ${predictions_dir}/spin_predictions
    # pixie: ${predictions_dir}/pixie_predictions
  
  smplx_models_paths:
    # smplx_male: /home/nadav2/dev/repos/Thesis/pre_production/smpl_male_e2e.ckpt
    # smplx_female: /home/nadav2/dev/repos/Thesis/pre_production/smpl_female_e2e.ckpt
    smplx_neutral: /home/nadav2/dev/repos/Thesis/pre_production/smpl_neutral_multiview_e2e.ckpt

  renderer_kwargs:
      img_size: [1024, 1024]
      dist: 4.2
      elev: 10.0
      azim: 0.0
      texture_optimization: True