[
"happy",
"sad",
"angry",
"surprised",
"disgusted",
"fearful",
"neutral",
"smiling",
"serious",
"pensive",
"confused",
"bored",
"sleepy",
"tired",
"excited",
"relaxed",
"calm",
"nervous",
"worried",
"scared",
"open mouth",
"raise eyebrows",
"open eyes",
"smile"
]