[
"short",
"tall",
"long legs",
"big",
"fat",
"broad shoulders",
"built",
"curvy",
"fit",
"heavyset",
"lean",
"long torso",
"long",
"muscular",
"pear shaped",
"petite",
"proportioned",
"rectangular",
"round apple",
"short legs",
"short torso",
"skinny",
"small",
"stocky",
"sturdy",
"narrow waist",
"thin"
]

