[
"fat",
"thin",
"hourglass",
"short",
"long legs",
"narrow waist",
"skinny",
"tall",
"broad shoulders",
"pear shaped",
"average",
"big",
"curvy",
"lean",
"proportioned",
"sexy",
"fit",
"heavyset",
"petite",
"small",
]