[
"short",
"tall",
"long legs",
"big",
"fat",
# "broad shoulders",
# "built",
"curvy",
"feminine",
"fit",
"heavyset",
"lean",
"long torso",
"long",
"masculine",
"muscular",
"pear shaped",
"petite",
"proportioned",
"rectangular",
"round apple",
"short legs",
"short torso",
"skinny",
"small",
"stocky",
"sturdy",
"attractive",
"sexy",
"narrow waist",
"hourglass"
]