[
  "Thin",
  "Muscular",
  "Athletic",
  "Fit",
  "Toned",
  "Lean", 
  "Stocky",
  "Chiseled",
  "Buff",
  "Ripped",
  "Strong",
  "Wiry",
  "Brawny",
  "Broad-shouldered",
  "Big-boned",
  "Robust",
  "Tall",
  "Overweight",
  "Slim"
]
