[
  'short', 'long legs', 'big', 'fat', 'broad shoulders', 'built', 'curvy', 'fit', 'heavyset', 'long torso', 'muscular', 'pear shaped', 'petite', 'proportioned', 'rectangular', 'round apple', 'short legs', 'short torso', 'skinny', 'sturdy', 'narrow waist'
]